### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by moonie878** [boxing/boxrec#249] opened 2020-09-18 14:52 UTC
I am having trouble setting this up does anyone have an example project? 

Kind Regards,

Mark

**Comment by mikedidomizio** [comment] 2020-09-18 18:42
Hey,

The best I can do at this time is below.  It should get you started.  Just a heads up that they've put in some measures to block/deny using automation.  If you spam requests, you'll be blocked.  As well as quick requests can trigger the captcha.  At this time I'd use with a BoxRec test account.

Hope this helps!

```
const boxrec = require("boxrec").Boxrec;

// as always do not commit these two lines.  Use environment variables or read from some temp file that doesn't get committed
 const boxrecUsername = "YOUR_USERNAME",
        boxrecPassword = "YOUR_PASSWORD";

    try {
         // we first log into boxrec with our credentials
        const cookieJar = await boxrec.login(boxrecUsername, boxrecPassword);
        // we pass the cookie along with the boxer ID that we want to retrieve
        const floydMayweather = await boxrec.getPersonById(cookieJar, 352);
        console.log(floydMayweather.name);
        console.log(floydMayweather.output);
    } catch (e) {
        console.log("this failed", e)
    }
```

**Comment by moonie878** [comment] 2020-09-18 23:03
Thank you very much. I think the issue is I am a noob at node. I believe I have figured it out with your snippet thank you.

**Comment by moonie878** [comment] 2020-09-18 23:58
I tried that and got all Mayweather's details apart from I can't seem to get his record - 
```
"record": {
            "draw": 0,
            "loss": 0,
            "win": 50
        },
```

I even checked all the data that is returned from 
`var record = floydMayweather;`

**Comment by mikedidomizio** [comment] 2020-09-19 12:27
If I understand correctly, I think the issue is you're looking at destructuring the variable but here you're assigning a variable.

Try this:

'''
const { record } = floydMayweather;
'''

which is the equivalent of assigning it like this

'''
const record = floydMayweather.record;
'''

Both do the same thing in this example.

I'm on mobile so hopefully this renders correctly.

**Comment by moonie878** [comment] 2020-09-19 23:01
Hi basically my issue is I can not get the record (win,loss,drawn) for Mayweather I have attached a screen shot of my results. 

![image](https://user-images.githubusercontent.com/14311345/93690782-4cfed000-fad4-11ea-9e07-60b2b4206ab2.png)
 
Kind regards

**Comment by mikedidomizio** [comment] 2020-09-22 15:36
I've been blocked by BoxRec at this time so I'm not sure when I'll be able to look into this.  It's possible that the HTML on BoxRec has changed and it's now defaulting to `undefined`.

I'll keep this issue open until I get a more definitive answer for you or the issue is resolved.

**Comment by moonie878** [comment] 2020-09-23 08:45
Oh no, I agree I think the html classes have been changed by boxrec. cheers Mark

**Comment by mikedidomizio** [comment] 2020-09-23 23:58
This issue should be fixed in `boxrec@7.1.2`.  This was an issue with the package.  When you can, let me know if `record` works for you.

**Comment by moonie878** [comment] 2020-09-24 00:27
awesome!! That worked I was on 7.1.1. Thank you for your help much appreciated

**Comment by mikedidomizio** [comment] 2020-09-24 00:41
Glad I could help out

**Closed by mikedidomizio** 2020-09-24 00:41 UTC
